### PR TITLE
Addressing Build errors

### LINKED ISSUE #13: I2C Build Conflict
I get the following error when attempting to build the latest version.

```
In file included from I2C.cpp:12:0:
/usr/include/linux/i2c-dev.h:38:8: error: redefinition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from ../include/I2C.h:13:0,
                 from I2C.cpp:8:
/usr/include/linux/i2c.h:68:8: error: previous definition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
 In file included from I2C.cpp:12:0:
/usr/include/linux/i2c-dev.h:90:7: error: redefinition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
In file included from ../include/I2C.h:13:0,
                 from I2C.cpp:8:
/usr/include/linux/i2c.h:128:7: error: previous definition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
```

I'm working on a fix and will have a pull request soon.

### PR DESCRIPTION
**Pull request by jadedanemone**
Fixes  #13 with a few extras:
- Removed Makefiles since they are generated by `./configure`
- Fixed the dts builds to update file references

### CODE REVIEW

**Comment by piranha32** [comment]
Please leave conversion to unsigned char in src/I2C.cpp
This is better readable, as on some architectures char may be signed 8 bit integer.

**Comment by jadedanemone** [comment]
After I change the include file, I get the following error:

```
I2C.cpp:307:10: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  msg.buf = (unsigned char *) rbuf;
```

Any advice on how to make this a valid conversion?

**Comment by jadedanemone** [comment]
As an alternative, the following language works for me. Thoughts?

```
msg.buf = (typeof(msg.buf)) rbuf;
```

**Comment by piranha32** [comment]
- Conversion of rbuf type looks ok for me, please submit as a separate patch unless you want me to make the change.
- I2C part builds cleanly. Is inclusion of i2c-dev.h necessary? I don't see a need for it.
- The issue with Makefiles has been addressed by another commit.

**Comment by jadedanemone** [comment]
I guess I need to go through the full explanation. In this pull request, I chased down errors I was having, and still have, with the source as provided. My system is a BeagleBone Black Rev C running Ubuntu 14.04.4 LTS with kernel 4.1.17-bone18 from Robert Nelson.

I ran the following commands just now to reconfirm the issues.

``` bash
git clone https://github.com/piranha32/IOoo.git
cd IOoo/
./configure
make
```

The `make` ends with the following error.

```
make[2]: Entering directory `/home/ubuntu/IOoo/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT I2C.o -MD -MP -MF .deps/I2C.Tpo -c -o I2C.o I2C.cpp
In file included from I2C.cpp:12:0:
/usr/include/linux/i2c-dev.h:38:8: error: redefinition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from ../include/I2C.h:13:0,
                 from I2C.cpp:8:
/usr/include/linux/i2c.h:68:8: error: previous definition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from I2C.cpp:12:0:
/usr/include/linux/i2c-dev.h:90:7: error: redefinition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
In file included from ../include/I2C.h:13:0,
                 from I2C.cpp:8:
/usr/include/linux/i2c.h:128:7: error: previous definition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
make[2]: *** [I2C.o] Error 1
make[2]: Leaving directory `/home/ubuntu/IOoo/src'
```

When I traced this through before, I found that include/I2C.h has `#include <linux/i2c.h>` and src/I2C.cpp has `#include <linux/i2c-dev.h>`. Both of these included files define `struct i2c_msg` and `union i2c_smbus_data`.

If I remove the "-dev" from the statement in src/I2C.cpp, I get:

```
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT I2C.o -MD -MP -MF .deps/I2C.Tpo -c -o I2C.o I2C.cpp
I2C.cpp: In member function ‘int I2C::open(int)’:
I2C.cpp:65:16: error: ‘I2C_FUNCS’ was not declared in this scope
  if (ioctl(fd, I2C_FUNCS, &supportedFuncs) < 0)
                ^
I2C.cpp: In member function ‘int I2C::setSlave(int, bool)’:
I2C.cpp:111:17: error: ‘I2C_TENBIT’ was not declared in this scope
   if (ioctl(fd, I2C_TENBIT, 1) < 0)
                 ^
I2C.cpp:140:16: error: ‘I2C_SLAVE’ was not declared in this scope
  if (ioctl(fd, I2C_SLAVE, slaveAddr) < 0)
                ^
I2C.cpp: In member function ‘int I2C::enablePEC()’:
I2C.cpp:265:16: error: ‘I2C_PEC’ was not declared in this scope
  if (ioctl(fd, I2C_PEC, 1) < 0)
                ^
I2C.cpp: In member function ‘int I2C::disablePEC()’:
I2C.cpp:279:16: error: ‘I2C_PEC’ was not declared in this scope
  if (ioctl(fd, I2C_PEC, 0) < 0)
                ^
I2C.cpp: In member function ‘int I2C::read(void*, size_t, bool, bool)’:
I2C.cpp:315:30: error: aggregate ‘I2C::read(void*, size_t, bool, bool)::i2c_rdwr_ioctl_data msgset’ has incomplete type and cannot be defined
   struct i2c_rdwr_ioctl_data msgset;
                              ^
I2C.cpp:319:17: error: ‘I2C_RDWR’ was not declared in this scope
   if (ioctl(fd, I2C_RDWR, &msgset) < 0)
                 ^
I2C.cpp: In member function ‘int I2C::write(const void*, size_t, bool)’:
I2C.cpp:358:30: error: aggregate ‘I2C::write(const void*, size_t, bool)::i2c_rdwr_ioctl_data msgset’ has incomplete type and cannot be defined
   struct i2c_rdwr_ioctl_data msgset;
                              ^
I2C.cpp:362:17: error: ‘I2C_RDWR’ was not declared in this scope
   if (ioctl(fd, I2C_RDWR, &msgset) < 0)
                 ^
I2C.cpp: In member function ‘int I2C::endTransaction()’:
I2C.cpp:481:29: error: aggregate ‘I2C::endTransaction()::i2c_rdwr_ioctl_data msgset’ has incomplete type and cannot be defined
  struct i2c_rdwr_ioctl_data msgset;
                             ^
I2C.cpp:486:16: error: ‘I2C_RDWR’ was not declared in this scope
  if (ioctl(fd, I2C_RDWR, &msgset) < 0)
                ^
make[2]: *** [I2C.o] Error 1
```

This was a little too much for me to work through. If instead I add the "-dev" to the statement in include/I2C.h, I get:

```
g++ -DHAVE_CONFIG_H -I. -I..  -I../include/  -D_HW_PLATFORM_BEAGLEBONE -DDEBUG_LEVEL=3   -g -O2 -std=gnu++11 -MT I2C.o -MD -MP -MF .deps/I2C.Tpo -c -o I2C.o I2C.cpp
I2C.cpp: In member function ‘int I2C::read(void*, size_t, bool, bool)’:
I2C.cpp:307:10: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  msg.buf = (unsigned char *) rbuf;
          ^
I2C.cpp: In member function ‘int I2C::write(const void*, size_t, bool)’:
I2C.cpp:350:10: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  msg.buf = (unsigned char *) wbuf;
          ^
make[2]: *** [I2C.o] Error 1
```

Replacing `unsigned char *` in both of these locations with `typeof(msg.buf)` fixes this error and results in a clean build.

**Comment by piranha32** [comment]
That's weird. It must be some incompatibility between Ubuntu and Debian. I've just compiled on Debian 8.3 fresh version of the library checked out from the repo and it built cleanly.
As I mentioned in my previous comment, I don't mind adding the cast to `typeof(msg.buf)`, but please commit the the modification as a standalone patch. Your previous patch combined many changes, some of them overlapped with modifications  done by other pulls. I can make the changes myself, but I prefer to give you a credit.
I really appreciate all contributions, but I have one, small request: could you please break combo patches into pulls addressing one issue each? It makes maintenance of the project much easier than dealing with big pulls addressing multiple issues.

**Comment by piranha32** [comment]
I think I know what causes the issue: old version of the kernel:
$uname -r
4.4.5-bone5

Anyway, cast to `typeof(msg.buf)` should make it compatible with current and future changes.

**Comment by jadedanemone** [comment]
I put the cast to `typeof(msg.buf)` in a separate pull request.

I've tried kernel 4.1.20-bone20, 3.8.13-bone79, and 4.4.6-bone6. No luck with any of them.

Since its i2c-dev.h and i2c.h that are not compatible:
i2c-dev.h is provided by the `libi2c-dev` package.

```
libi2c-dev:
  Installed: 3.1.0-2
  Candidate: 3.1.0-2
  Version table:
 *** 3.1.0-2 0
        500 http://ports.ubuntu.com/ubuntu-ports/ trusty/universe armhf Packages
        100 /var/lib/dpkg/status
```

i2c.h is provided by `linux-libc-dev`:

```
linux-libc-dev:
  Installed: 3.13.0-83.127
  Candidate: 3.13.0-83.127
  Version table:
 *** 3.13.0-83.127 0
        500 http://ports.ubuntu.com/ubuntu-ports/ trusty-updates/main armhf Packages
        100 /var/lib/dpkg/status
     3.13.0-24.46 0
        500 http://ports.ubuntu.com/ubuntu-ports/ trusty/main armhf Packages
```

**Comment by piranha32** [comment]
Ubuntu is a bit behind debian 8.3. This is what I have:
libi2c-dev: 3.1.1-1
linux-libc-dev: 3.16.7-ckt20-1+deb8u4

**Pull request closed without merging**
