### PR TITLE
Sod it merge the lot

### PR DESCRIPTION
**Pull request by CJxD**
It became increasingly difficult to split these up atomically so I just decided to give you the chance to merge it all first. Otherwise, I'll see what I can split.

Goodies:
Added autoconf checks for a compatible DTC - able to specify your own DTC with configure --with-dtc=/path/to/dtc
EEPROM chip support
I2C improvements
SPI improvements (including thread safety)
Support both version 3.x and version 4.x kernels (who have different naming for I2C and SPI buses)
Able to create both .a and .so files (the latter is kinda a requirement for the LGPL)

### CODE REVIEW

**Comment by piranha32** [comment]
One thing I really don't like is that the patch drags a bunch of copyrighted TI code from pruss lib. What is it used for?

**Comment by CJxD** [comment]
No idea. You used it in TLC5946PRUSSphy.cpp and originally linked directly to a precompiled libprussdrv.a file (which causes issues when you try to create a shared library unless it's compiled with -fPIC).

The code is free to use with that copyright statement in. In fact, the copyright statement should be provided with the .a files that currently exist anyway.

Or we could just drop TLC5946PRUSSphy.cpp and not worry about it

**Comment by piranha32** [comment]
libprussdrv is an external dependency and should not be included in the library. TLC5946PRUSSphy.cpp is an implementation of a driver for TLC5946 which uses PRU to generate clock signal, and may be dropped from build if libprussdrv is not available.

**Comment by CJxD** [comment]
Okay so I'll put in a check in configure.ac for libprussdrv and if it doesn't exist, no PRUSS modules will be compiled

**Comment by piranha32** [comment]
I'm fine with some kind of manual switch, e.g. --with-prussdrv-lib and --with-prussdrv-include

**Comment by CJxD** [comment]
But would that require still having libprussdrv.a in the git repo? Or do you mean to have the user point to an existing installation they have?

**Comment by piranha32** [comment]
Anywhere on the filesystem, but not in the repo. libprussdrv does not belong here.

**Comment by CJxD** [comment]
I have implemented an automatic check for libprussdrv. If it finds both the library and the header files from standard paths it will compile TLC5946PRUSSphy.cpp, otherwise it won't.

I have also implemented --with-prussdrv-lib=DIR and --with-prussdrv-include=DIR but the general consensus is that the maintainer should not implement stuff like this; the user should add it to LDFLAGS and CPPFLAGS themselves:

`LDFLAGS=$LDFLAGS -L/path/to/prussdrv/lib`
`CPPFLAGS=$CPPFLAGS -I/path/to/prussdrv/include`

Should I follow this advice or keep in the --with statements?

**Comment by CJxD** [comment]
Is this okay to merge now or are there any other changes needed?

**Comment by piranha32** [comment]
Sorry, I just noticed the request.

**Pull request merged**
